#!/bin/make -f
# file: Makefile
all: es91

# Ricordarsi la linea vuota come separatore
# formato della regola = obiettivo: dipendenze
es91: es91.c es91b.c
	gcc -Wall -o es91 es91.c es91b.c
# Ricordarsi del tab all'inizio di ogni comando

# fine file

